--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -394,3 +394,5 @@
 obj-$(CONFIG_DEBUG_FS) += msm_cpr-debug.o
 endif
 obj-$(CONFIG_MSM_CPU_PWRCTL) +=  msm_cpu_pwrctl.o
+
+obj-$(CONFIG_ARCH_RANDOM) += early_random.o
